# Site settings
title: UX Design & Front End Development Portfolio for Brandon Reid
email: brandonreidak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brandon Reid is a UX Designer & Front End Developer in California, also co-founder of Benchmark Intelligence.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://brandonreid.github.io/portfolio/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['js',
          'img',
          'blog-images',
          'css',
          'fonts']
exclude: ['_less',
          'node_modules/',
          'gulpfile.js',
          'package.json',
          'README.md']

# Navigation
navigation:
- text: Portfolio
  url: /
  class: portfolio-page
# - text: Blog
#   url: /blog/
#   class: blog-page
# - text: About
#   url: /about/
#   class: about-page
